apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- vote-deployment.yaml
- vote-service.yaml
configMapGenerator:
- name: vote
  literals:
  - OPTION_A=CANDY
  - OPTION_B=CANE
images:
- name: usmanlakhani/vote
  newTag: main-8dde94a2-1709839377 # {"$imagepolicy": "flux-system:vote:tag"}
