apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- vote-deployment.yaml
- vote-service.yaml

configMapGenerator:
  - name: vote
    literals:
      - OPTION_A=CANDY
      - OPTION_B=CANE


